In [1]:
import PIL
from cv2 import *
from pyMez.Code.DataHandlers.Translations import *

Importing pyMez, this should take roughly 30 seconds
Importing Code.DataHandlers.GeneralModels
It took 0.327 s to import Code.DataHandlers.GeneralModels
Importing Code.DataHandlers.HTMLModels
It took 0.696 s to import Code.DataHandlers.HTMLModels
Importing Code.DataHandlers.NISTModels
It took 13.406 s to import Code.DataHandlers.NISTModels
Importing Code.DataHandlers.TouchstoneModels
It took 0.017 s to import Code.DataHandlers.TouchstoneModels
Importing Code.DataHandlers.XMLModels
It took 0.49 s to import Code.DataHandlers.XMLModels
Importing Code.DataHandlers.ZipModels
It took 0.06 s to import Code.DataHandlers.ZipModels
Importing Code.InstrumentControl.Experiments
It took 1.968 s to import Code.InstrumentControl.Experiments
Importing Code.InstrumentControl.Instruments
It took 0.016 s to import Code.InstrumentControl.Instruments
Importing Code.Utils.Names
It took 0.013 s to import Code.Utils.Names
It took 16.994 s to import all of the active modules


In [7]:
camera_1=r"C:\Share\CubeOfScience\PlusX.jpg"
camera_2=r"C:\Share\CubeOfScience\MinusX.jpg"
camera_3=r"C:\Share\CubeOfScience\PlusY.jpg"
camera_4=r"C:\Share\CubeOfScience\MinusY.jpg"

In [8]:
image_list=[File_to_Image(camera) for camera in [camera_1,camera_2,camera_3,camera_4]]

In [13]:
image_list_2=[im.load() for im in image_list]

In [24]:
test=image_list[0]

In [31]:
np.array(test.getpixel((0,0)))/np.mean(test.getpixel((0,0)))

array([ 1.33603239,  0.95951417,  0.70445344])

In [ ]:
test.putpixel()

In [70]:
def filter_by_color(image,r,g,b,delta_r,delta_g,delta_b):
    """Returns an image filtered by color """
    image=image.copy()
    for i in range(image.size[0]):
        for j in range(image.size[1]):
            pixel_value=image.getpixel((i,j))
            if abs(pixel_value[0]-r)<delta_r:
                if abs(pixel_value[1]-g)<delta_g:
                    if abs(pixel_value[2]-b)<delta_b:
                        pass
            else:
                image.putpixel((i,j),(0,0,0))
                
    return image

def green_filter(image,filter_constant=1):
    """Returns an image filtered by color """
    image=image.copy()
    for i in range(image.size[0]):
        for j in range(image.size[1]):
            pixel_value=image.getpixel((i,j))
            filter_array=map(lambda x: x/np.mean(pixel_value),pixel_value)
            if filter_array[1]>filter_constant:
                pass
            else:
                image.putpixel((i,j),(0,0,0))
                
    return image
def green_filter_2(image,filter_constant=1):
    """Returns an image filtered by color """
    new_image=PIL.Image.new(mode="RGB",size=image.size)
    for i in range(image.size[0]):
        for j in range(image.size[1]):
            pixel_value=image.getpixel((i,j))
            filter_array=map(lambda x: x/np.mean(pixel_value),pixel_value)
            if filter_array[1]>filter_constant:
                new_image.putpixel((i,j),pixel_value)
            else:
                pass
                
    return new_image
               

In [47]:
filters=[1.0,1.1,1.2,1.3]
names=["plus_x","minus_x","plus_y","minus_y"]
directory=r"C:\Share\FilterCube"
for name_index,image_name in enumerate(image_list):
    for filter1 in filters:
        file_name=os.path.join(directory,names[name_index]+str(filter1).replace(".","_")+".jpg")
        new_image=green_filter(image_name,filter1)
        new_image.save(file_name)


In [ ]:
new_image.

In [39]:
new_image.show()

In [43]:
size=image_list[0].size
image=image_list_2[0]
filter_constant=1.2
for i in range(size[0]):
    for j in range(size[1]):
        pixel_value=image[i,j]
        filter_array=np.array(pixel_value)/np.mean(pixel_value)
        if filter_array[1]>filter_constant:
            pass
        else:
            pixel_value=(0,0,0)

In [44]:
image.show()

AttributeError: 'PixelAccess' object has no attribute 'show'

In [50]:
size_reduction_ratio=8
new_size=np.array(image_list[0].size)/size_reduction_ratio
new_size=map(lambda x:int(x),new_size.tolist())
resized_image_list=[]
for image_name in image_list[:]:
    resized_image_list.append(image_name.resize(new_size))

In [51]:
resized_image_list[0].show()

In [65]:
resized_filter_image_list=map(lambda x: green_filter(x,1.1),resized_image_list)

In [71]:
resized_filter_image_list_2=map(lambda x: green_filter_2(x,1.1),resized_image_list)

In [72]:
resized_filter_image_list_2[0].show()

In [66]:
rotations=[180,270,90,0]
resized_rotated_filter_list=[]
for image_index,image_name in enumerate(resized_filter_image_list):
    resized_rotated_filter_list.append(image_name.rotate(rotations[image_index]))

In [ ]:
rotations=[180,270,90,0]
resized_rotated_filter_list=[]
for image_index,image_name in enumerate(resized_filter_image_list):
    resized_rotated_filter_list.append(image_name.rotate(rotations[image_index]))

In [68]:
resized_rotated_filter_list[3].size

(504, 378)

In [ ]:
locations=[(14,0,36),(-14,0,36),(0,12.5,36),(0,-12.5,0)]

In [108]:
directory=r"C:\Share\FilterCube\ReducedSizeFiltered"
names=["plus_x","minus_x","plus_y","minus_y"]
for image_index,image_name in enumerate(resized_rotated_filter_list):
    name=os.path.join(directory,names[image_index]+".jpg")
    image_name.save(name)

In [114]:
centers=[(221,210),(262.25,211),(236,156.5),(311.75,187.25)]
ideal_center=(504/2,378/2)
translations=map(lambda x:np.array(x)-np.array(ideal_center),centers)

In [115]:
translations=map(lambda x: x.tolist(),translations)

In [111]:
translations

[[-186, 21], [10.25, 22.0], [-16.0, -32.5], [59.75, -1.75]]

In [116]:
translated_image_list=[]
for image_index,image_name in enumerate(resized_rotated_filter_list[:]):
    if image_index in [0,3]:
        move=1
    else:
        move=1
    a = 1
    b = 0
    c = move*translations[image_index][0] #left/right (i.e. 5/-5)
    d = 0
    e = 1
    f = move*translations[image_index][1] #up/down (i.e. 5/-5)
    translated_image_list.append(image_name.transform(image_name.size,Image.AFFINE,(a, b, c, d, e, f)))

In [117]:
directory=r"C:\Share\FilterCube\Translated"
names=["plus_x","minus_x","plus_y","minus_y"]
for image_index,image_name in enumerate(translated_image_list):
    name=os.path.join(directory,names[image_index]+".jpg")
    image_name.save(name)

In [ ]:
img = Image.new('RGB', (100, 100), 'red')
a = 1
b = 0
c = 0 #left/right (i.e. 5/-5)
d = 0
e = 1
f = 0 #up/down (i.e. 5/-5)
img = img.transform(img.size, Image.AFFINE, (a, b, c, d, e, f))
img.save('image.png')

In [122]:
def distance_from_size(size):
    "Returns the distance in inches from a phone camera given the size of a standard cube in pixels (cube is 1.75 inches)"
    return (np.exp(-1/1.075*np.log(size/7077.6)))

In [124]:
distance_from_size(163)

33.376468373589759

In [2]:
position1_directory=r"C:\Share\CubeOfScience_2_20180224\Position1"
position2_directory=r"C:\Share\CubeOfScience_2_20180224\Position2"
position3_directory=r"C:\Share\CubeOfScience_2_20180224\Position3"

In [3]:
def distance_from_size_cube2(size):
    "Returns the distance in inches from a phone camera given the size of a standard cube in pixels (cube is 2 inches)"
    return (np.exp(-1/.995*np.log(size/6437.4)))


In [17]:
image_name_list=os.listdir(position2_directory)
image_list=[File_to_Image(os.path.join(position2_directory,name)) for name in image_name_list]

In [23]:
rotations=[180,270,0,90]
rotated_list=[]
for image_index,image_name in enumerate(image_list[:]):
    rotated_list.append(image_name.rotate(rotations[image_index]))

In [24]:
for image in rotated_list[:]:
    image.show()

In [26]:
for image_index,image in enumerate(rotated_list[:]):
    image.save(os.path.join(r"C:\Share\CubeOfScience_2_20180224\Positon2_Rotated",image_name_list[image_index]))

In [28]:
#Blue Tape
color = np.uint8([[[80,98,70 ]]])
hsv_color = cv2.cvtColor(color,cv2.COLOR_BGR2HSV)
print(hsv_color)
#Green Cube
color = np.uint8([[[211,235,111 ]]])
hsv_color = cv2.cvtColor(color,cv2.COLOR_BGR2HSV)
print(hsv_color)

[[[71 73 98]]]
[[[ 84 135 235]]]


In [30]:
#Blue_tape
print np.array([80,98,70 ])/np.mean([80,98,70 ])
#green_cube
print np.array([211,235,111 ])/np.mean([211,235,111 ])

[ 0.96774194  1.18548387  0.84677419]
[ 1.13644524  1.26570916  0.5978456 ]


In [ ]:
import cv2
import numpy as np
cap = cv2.VideoCapture(0)
while(1):
    # Take each frame
    _, frame = cap.read()
    # Convert BGR to HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    # define range of blue color in HSV
    lower_blue = np.array([110,50,50])
    upper_blue = np.array([130,255,255])
    # Threshold the HSV image to get only blue colors
    mask = cv2.inRange(hsv, lower_blue, upper_blue)
    # Bitwise-AND mask and original image
    res = cv2.bitwise_and(frame,frame, mask= mask)
    cv2.imshow('frame',frame)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break
cv2.destroyAllWindows()